### ISSUE TITLE
No getting started ?

### ISSUE THREAD

**Issue by sboudouk** [okode/cordova-plugin-twilio-video#10]
Hello.

I'm actually using Twilio Video for my project and developped it through react. It works and I can join video rooms and chat as expected.

Since i'm completly new to Cordova, I wanted to know if your plugin is needed to make it work on an Android phone for example ?

Thank you.

**Comment by rpanadero** [comment]
We are about to release a new major version which will include breaking changes. By then, we will try to improve our docs.

**Comment by jandieg** [comment]
Looking forward. I should be starting a Cordova project with Web RTC.

**Comment by aveeday** [comment]
> We are about to release a new major version which will include breaking changes. By then, we will try to improve our docs.

very interesting what new features will be in new version

it would be nice to have ability to make "audio only" calls without video on/off ui

**Comment by rpanadero** [comment]
README was improved.
