### ISSUE TITLE
Does this plugins work on iOS ? 

### ISSUE THREAD

**Issue by sboudouk** [okode/cordova-plugin-twilio-video#15]
I am struggling to get my Twilio Video implementation works on iOS due to getUserMedia incompatiblity. 

Do this plugin get rid of this ?

**Comment by jonathanrevell** [comment]
I recently got it set up in iOS, works great.

**Comment by sboudouk** [comment]
Thanks for your answer @jonathanrevell .

Did you use Ionic with Capacitor or Corodva only ?

**Comment by mfkenson** [comment]
@sboudouk I believe this plugin only does the job on openRoom and closeRoom by wrapping the native twilio SDK. Other stuff such as what you mentioned have to be done separately. I would perform other operations (user auth, create room, etc) on my backend server.

**Comment by sboudouk** [comment]
@mfkenson  Yeah I think so. I already use Twilio Video successfully on Android, but on iOS, there is no webRTC so It does not work. I'm very curious to know how people manage to make Twilio-Video work on iOS.

**Comment by mfkenson** [comment]
@sboudouk Instead, I successfully run the ionic app (ionic 5 with capacitor) using this plugin on my iPhone and iPad. However I failed to run the app on Android Phone.

I created the room (hence obtained the roomID), generated two access tokens on my laptop using NodeJS Twilio library. Then manually passed these data to the ionic app.

**Comment by sboudouk** [comment]
@mfkenson You manage to get a functionnal room with remote and local participants video running ?

Would you mind sharing code ? Because I am struggling for days now on iOS trying to get getUserMedia works.

**Comment by mfkenson** [comment]
@sboudouk I have to refactor my code first. I could show you these 2 photos right now.
One is Android One phone and the other one is iPad.

1. Make sure user granted the permissions by calling 
`TwilioVideo.hasRequiredPermissions` and `TwilioVideo .requestPermissions`

2. Use valid access token and roomID.

3. `TwilioVideo.openRoom `

![ui](https://user-images.githubusercontent.com/1910865/80738355-7c259c80-8b47-11ea-827b-81b1be546b36.jpg)
![android-ipad](https://user-images.githubusercontent.com/1910865/80738372-847dd780-8b47-11ea-9871-4ae629859da2.jpg)

**Comment by sboudouk** [comment]
Thank you for sharing.

Is this UI provided by this cordova plugin ? I would be curious on how did you manage to get it worked on iOS, so I am waiting for the code patiently, thanks again @mfkenson .

**Comment by clemevi** [comment]
I also have problems on ios, after giving permissions to the app I keep getting this error: _Call to getUserMedia failed_

@mfkenson How did you get it running on ios?

**Comment by rpanadero** [comment]
Both android and ios plugins ask for permissions when the `openRoom` method is invoked. I cannot reproduce the issue. Could anybody share the code?

**Comment by sboudouk** [comment]
> Both android and ios plugins ask for permissions when the `openRoom` method is invoked. I cannot reproduce the issue. Could anybody share the code?

How do you manage to get videoStream on iOS since webRTC is not supported ?

**Comment by Suhas-ap** [comment]
I want to customize this plugin so that there will small window which I can show for the video calling (like an overlay- Assistive Touch), right now there is a full screen showing up, what you will suggest to me to perform this operation.

**Comment by rpanadero** [comment]
> > Both android and ios plugins ask for permissions when the `openRoom` method is invoked. I cannot reproduce the issue. Could anybody share the code?
> 
> How do you manage to get videoStream on iOS since webRTC is not supported ?

As for as I know, there is WebRTC support on native iOS and browser from a specific iOS version, but not in webview. For that reason, Twilio Video has to be natively integrated in a Cordova app.

In addition, you have to take into account this plugin just integrates Twilio Video SDK, that is, we directly don't use any WebRTC library.

**Comment by rpanadero** [comment]
> I want to customize this plugin so that there will small window which I can show for the video calling (like an overlay- Assistive Touch), right now there is a full screen showing up, what you will suggest to me to perform this operation.

I'm sorry, but it is not possible to do what you want by using this plugin. If you want to do something like that, I would recommend you to change the implementation of this plugin to fit your purpose. At the moment, we don't have intention to support that feature, sorry.
