### ISSUE TITLE
Undefined in capacitor

### ISSUE THREAD

**Issue by alokjkumar** [okode/cordova-plugin-twilio-video#17]
Can you give some more guidance on how to implement this in Capacitor with Ionic?

I tried using the global `window` object as you suggested:

`window.twiliovideo.openRoom(token, roomId)`

but this gives:

`Property 'twiliovideo' does not exist on type 'Window & typeof globalThis'.`

I also tried importing it directly into the file with

```
import 'cordova-plugin-twilio-video';

//...
twiliovideo.openRoom(token, roomId);
// also tried
window.twiliovideo.openRoom(token, roomId);
```

but then just get 

`Cannot find name 'twiliovideo'.`

I also tried importing it with Capacitor Plugins

```
import { Plugins } from '@capacitor/core';
const TwilioVideo = Plugins.twilioVideo;

//...
TwilioVideo.openRoom(token, roomId);
```

This compiles but get a runtime error in LogCat: 

`TypeError: Cannot read property 'openRoom' of undefined`

I'm at a wit's end, would really appreciate some guidance. Thanks.

EDIT:

Also tried this:
```
import { TwilioVideoPlugin } from 'cordova-plugin-twilio-video';
declare const TwilioVideo: TwilioVideoPlugin;
```
but get
`Cannot find module 'cordova-plugin-twilio-video'.`

**Comment by mfkenson** [comment]
You may want to paste this into your ts file to get around from lint 

```
declare global {
  interface Window { twiliovideo: any; }
}

window.twiliovideo = window.twiliovideo || {};
```

**Comment by alokjkumar** [comment]
This seems to have fixed it, thank you :)
