### ISSUE TITLE
window.twiliovideo.openRoom doesn't work - IONIC 5

### ISSUE THREAD

**Issue by neerajsaxena0711** [okode/cordova-plugin-twilio-video#18]
I have followed the instructions, and installed the plugin for my cordova ionic 5 project. 

`{
  "name": "videoSample",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "cordova-android": "8.1.0",
    "cordova-plugin-androidx": "^2.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-twilio-video": "https://github.com/okode/cordova-plugin-twilio-video",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-twilio-video": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {}
    },
    "platforms": [
      "android"
    ]
  }
}`

That's my package.json file. 
Now in my .ts file, I am just calling the function - `  joinCall(){
    window.twiliovideo.openRoom(this.token, this.room)
  }`

I have granted the necessary permissions for mic and camera, so is this all I need to do?
I have generated the token and the room from the twilio developer account. 
The token I am passing is the one that get's generated when we create a room.

Is there any thing wrong that I am doing?

**Comment by neerajsaxena0711** [comment]
I got this to work, so using Twilio cli, I created a meeting - `twilio api:video:v1:rooms:create \
    --record-participants-on-connect  \
    --status-callback http://example.org \
    --type group \
    --unique-name DailyStandup`

Then I generated an access token for the room called - DailyStandup using this - 
https://www.twilio.com/console/video/project/testing-tools

Then passed these as the params on - 
`        window.twiliovideo.openRoom(this.token, this.room,  (res)=>{console.log(res)}, {})`

So the "call connected" event got fired. Now the interesting thing that happens is when the other app, using the same credentials joins the same meet, the call on the initial app automatically disconnects with an event "call disconnected". 

How do 2 people join the same room?

**Comment by rpanadero** [comment]
The plugin just support calls for two people and both must use different credentials. If you use the same credentials for both people, it is the expected behavior what you are seeing. So, you have to generate different access tokens for each person.
