### ISSUE TITLE
Turn off full screen view

### ISSUE THREAD

**Issue by TravBradfield** [okode/cordova-plugin-twilio-video#19]
This plugin is great and is working like a charm! 
 
I don't want the video to open in full screen mode. How do I adjust the size of the video elements? 

Thanks.

**Comment by rpanadero** [comment]
I'm sorry, but this plugin doesn't support that feature and, at the moment, we don't have intention to support it. However, feel free to open a PR and we'll have a look at it.

Thanks anyway,
