### ISSUE TITLE
After connecting is there a way to get the participants in a room? (Or other room data?)

### ISSUE THREAD

**Issue by thephpguy** [okode/cordova-plugin-twilio-video#28]
With twilio-video you can normally call something like this and get the room object returned.

```
connect(this.twilioAuthToken, {
	name: twilioRoomId,
	audio: { ... },
	video: { ...}
}).then((room: Room) => {
	console.log(room.participants);
});
```

With this plugin after connecting I am not able to get the participants in a room.

```
(window as any).twiliovideo.openRoom(
	twilioAuthToken,
	twilioRoomId,
	((ev) => {
		this.twilioEvent(ev);
		console.log(ev);
	}),
	config
);
```

Is there a way to get the participants in a room? If not is there any plan to add this functionality to the plugin?

**Comment by rpanadero** [comment]
It is not expected to add this feature to the plugin
