### ISSUE TITLE
A question about logs

### ISSUE THREAD

**Issue by mozhn** [okode/cordova-plugin-twilio-video#29]
I started using the plugin. However, my users suddenly returned that the connection was disconnected. In my scenario, when a user leaves the call, it is to pull everyone out. I do this when I get the **PARTICIPANT_DISCONNECTED** information. Even your slightest thought about the subject is important to me.

**Comment by rpanadero** [comment]
What do you exactly do when you get PARTICIPANT_DISCONNECTED event?

**Comment by mozhn** [comment]
Yes I am invoke there is no problem in this regard. What I'm wondering is in what scenarios the event I'm talking about takes place.
