### ISSUE TITLE
Videopreview orientation problem, maybe upgrade to iOS Twilio SDK to 2.5.5

### ISSUE THREAD

**Issue by allnash** [okode/cordova-plugin-twilio-video#4]
I am facing the following issue on iOS builds on iPhone X. Would it be possible to upgrade the Podspec to use `2.5.5`?

https://github.com/blackuy/react-native-twilio-video-webrtc/issues/161

Thanks,

**Comment by allnash** [comment]
Just tested locally, and it seems to build with the latest Xcode 11.1 + Catalina + Cordova 9.0 + Cordova iOS 5.0.1.

**Comment by rpanadero** [comment]
@allnash thank you for the report, we will have a look at the new SDK as soon as possible.

**Comment by allnash** [comment]
@rpanadero any update on this?

**Comment by rpanadero** [comment]
Done! A new version was released `3.2.0`.

**Comment by allnash** [comment]
.🎉👍
