### ISSUE TITLE
Capacitor: ERROR: Manifest merger failed

### ISSUE THREAD

**Issue by rabinhod** [okode/cordova-plugin-twilio-video#6]
Hi
I want to use this plugin in my Capacitor Ionic app
after add in my project when i want to build i get error

i test it in fresh project but it's get error
i do it like this

1-`ionic start myApp tabs --capacitor`

2-`cd myApp`

3-`npx cap init myApp com.example.com`

4-`Add this dependency to 'package.json':`
`"dependencies": {`
`...`
`"cordova-plugin-twilio-video": "https://github.com/okode/cordova-plugin-twilio-video",`
`...`
`}`

5-`npm install`

6-`ionic build`

7-`npx cap add android`

8-`npx cap sync`

9-`npx cap copy`

10-`npx cap open android`

and i run program in android studio and get this error !

`ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-43:19 to override.
`

**Comment by rpanadero** [comment]
I guess that the error isn't due to this plugin, could you tell me all dependencies that your project have? Have a look at your `package.json` and the gradle depencies of your Android project. You may have a gradle dependency that brings androidx libraries which are incompatible with other dependencies that use `android.support`.

**Comment by rabinhod** [comment]
package.json

> {
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/android": "^1.3.0",
    "@capacitor/core": "1.3.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1",
    "cordova-plugin-twilio-video": "https://github.com/okode/cordova-plugin-twilio-video"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@capacitor/cli": "1.3.0",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"
}


build.gradle(Project: android)
> dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }


build.gradle(Module: app)
> dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation project(':capacitor-android')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':capacitor-cordova-android-plugins')
}

build.gradle(Module: capacitor-android)
> dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-compat:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:customtabs:28.0.0'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'org.apache.cordova:framework:7.0.0'
}

build.gradle(Module: capacitor-cordova-android-plugins)
> dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.jar'])
    implementation 'org.apache.cordova:framework:7.0.0'
    // SUB-PROJECT DEPENDENCIES START
    implementation "com.google.android.gms:play-services-gcm:+"
    implementation "com.android.support:appcompat-v7:26+"
    // SUB-PROJECT DEPENDENCIES END
}

**Comment by rpanadero** [comment]
The dependency that makes your build fail is: `implementation "com.google.android.gms:play-services-gcm:+"`. The last version of this dependency brings `androidx`. Try to force a specific version.

**Comment by rabinhod** [comment]
Thank you
I remove that dependency and run again
i get this error !

> INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: capacitor-android


capacitor-android point to build.gradle(Module: capacitor-android)

**Comment by rabinhod** [comment]
I remove that dependency and it's work
Thank you ;)
