### ISSUE TITLE
How to use in Capacitor ?

### ISSUE THREAD

**Issue by rabinhod** [okode/cordova-plugin-twilio-video#7]
I add it successfully to my Capacitor Ionic project 
how can i use it ?
in my program users most pay and then they can connect to some consultants
could you please explain what i should do ?

**Comment by rpanadero** [comment]
Sorry, but I consider that this is not an issue. We don't provide support in Twilio usage. This plugin just allows Cordova/Capacitor applications to open a twilio video conference and handle events , triggered from the native side, in the web side.

I would suggest you to get in touch with Twilio support team.

**Comment by rabinhod** [comment]
You right but i don't know how can i use it in Capacitor !
Can you give me sample code in Capacitor Ionic ?
Thank you
